import { StyleSheet } from "react-native";

export const SearchStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#0A0B19",
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    paddingLeft: 27,
    gap: 16,
    height: 35,
  },
  headerTitle: { color: "#FFFFFF", fontSize: 18, fontFamily: "Syne-Bold" },
  firstContainer: {
    marginTop: 40,
    paddingHorizontal: 25,
  },
  addCoverText: {
    fontSize: 16,
    fontFamily: "Poppins-Medium",
    color: "#FFFFFF",
  },
  imageView: {
    height: 120,
    width: 120,
    borderRadius: 12,
    borderStyle: "dashed",
    borderWidth: 2,
    borderColor: "#FFFFFF20",
    backgroundColor: "#191A2A",
    justifyContent: "center",
    alignItems: "center",
  },
  shortlistView: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#FFFFFF50",
    backgroundColor: "#171722",
    fontSize: 16,
    fontFamily: "Poppins-Regular",
    justifyContent: "flex-start",
    textAlignVertical: "top",
    height: 50,
    paddingLeft: 20,
  },
  descriptionView: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#FFFFFF50",
    backgroundColor: "#171722",
    fontSize: 16,
    fontFamily: "Poppins-Regular",
    height: 100,
    paddingLeft: 20,
  },
  listView: {
    flexDirection: "row",
    alignItems: "center",
    marginVertical: 3,
  },
  imagestyle: {
    height: 56,
    width: 56,
    borderRadius: 50,
    marginHorizontal: 12,
    paddingTop: 30,
  },
  seperator: {
    height: 1,
    backgroundColor: "#FFFFFF20",
    marginHorizontal: 20,
  },
  iconStyle: {
    marginRight: 20,
    top: 22,
    // backgroundColor: "white",
  },
  statsRow: {
    flexDirection: "row",
    alignItems: "center",
    flexWrap: "wrap",
    marginLeft: 35,
    left: 43,
    bottom: 20,
    fontSize: 12,
  },
  statsText: {
    color: "#FFFFFF70",
    fontSize: 12,
    marginLeft: 4,
    fontFamily: "Poppins-Regular",
    marginRight: 10,
  },
  selectText: {
    color: "#FFFFFF",
    fontSize: 14,
    fontFamily: "Poppins-Medium",
    marginHorizontal: 12,
  },
  listName: {
    fontSize: 16,
    flex: 1,
    color: "white",
    fontFamily: "Syne-SemiBold",
  },
  listUsername: {
    color: "#FFFFFF70",
    marginLeft: 35,
    left: 45,
    bottom: 20,
    fontSize: 12,
    fontFamily: "Poppins-Regular",
  },
  buttonView: {
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#495AFF",
    margin: 15,
    borderWidth: 1,
    height: 50,
  },
  buttonText: {
    fontFamily: "Poppins-Medium",
    fontSize: 16,
    color: "#FFFFFF",
  },
});
